spring.application.name=user
spring.application.version=1.0.0

server.port=8080
datasource.url=jdbc:postgresql://localhost:5435/user_db
datasource.username=user_db
datasource.password=user_db

jpa.hibernate.ddl-auto=update
jpa.show-sql=true

flyway.enabled=true
flyway.locations=classpath:db/migration


